### ISSUE TITLE
Major redesign (version 2)

### ISSUE THREAD

**Issue by jbsarrodie** [archi-contribs/jarchi-single-page-html-export#11]
Current version works great, but while working on #7 (Allow deeplinks to easily bookmark one specific view) and #10 (Report mode with AlaSql) it became obvious that current HTML/CSS code was a bit of a mess.

So I decided to reboot and to start again using gain knowledge as a starting point. I now have the basic skeleton up and running (and documented) and will be able to share it soon.

**Comment by Phillipus** [comment]
> was a bit of a mess.

Well, it wasn't that bad. 😉 But, OK, thanks for the work on this!

**Comment by jbsarrodie** [comment]
>Well, it wasn't that bad. 

Yes, but there are tons of hacks and CSS things I don't even understand ;-)

The new version will have the same look but:
- It will have two levels of navigation: when JS is enabled, a sidebar's footer will provide access to several "modes". The default one will be "View Visualizer", but there should be also a "SQL Query" and a "DataVisualization" mode.
- Each and every CSS line will be documented
- I'll do a better usage of semantic tags and classes

Here is a screenshot of the work in progress (nothing fanzy):
![image](https://user-images.githubusercontent.com/5757396/78636895-8ab2c800-78a9-11ea-9147-2015dc51eaae.png)

**Comment by Phillipus** [comment]
> Yes, but there are tons of hacks and...things I don't even understand ;-)

Yes I know the feeling...Eclipse.

**Comment by jbsarrodie** [comment]
The new version is now available. It has the exact same feature set as the previous version, but will be really easier to maintain and extend.
