### ISSUE TITLE
The new version of the report is no more compatible with IE11

### ISSUE THREAD

**Issue by jbsarrodie** [archi-contribs/jarchi-single-page-html-export#13]
This has to be fixed...

**Comment by Phillipus** [comment]
Any particular thing?

**Comment by jbsarrodie** [comment]
I have to investigate (I just wanted to make sure it was traced here).

Possible reasons:
- New version of the report uses HTML5 tags like main, nav, article, section, header...
- New version of the report uses more CCS3 things like var(), calc(), :not()...
- IE11 never works as expected :-)

FWIW, Chrome, Edge, Firefox and Opera work.

**Comment by jbsarrodie** [comment]
I did some investigations and tests, and hee is a list of known issues to be fixed (hopefull not too complicated):

- [x] **IE11 doesn't support CSS variables**, so I have to use templating system to still make it somewhat dynamic and manageable. But this means that I no longuer can load the template in a browser without first "compiling" it.
- [x] **IE11 doesn't support font ligatures**, so I simply have to use char codes (not a big deal)
- [x] **IE11 doesn't support 'initial' CSS value**, so I have to set the real value (when known)
- [ ] ~**IE11 has some issues with z-index**~

**Comment by jbsarrodie** [comment]
Solved by latest commit.

**Comment by Phillipus** [comment]
😮
