### ISSUE TITLE
Always use hamburger icon

### ISSUE THREAD

**Issue by jbsarrodie** [archi-contribs/jarchi-single-page-html-export#2]

**Comment by Phillipus** [comment]
FYI - a hamburger icon is used in both states in Firefox and Mac Notifications.

**Comment by jbsarrodie** [comment]
Yes, that's also true on GMail and Outlook, so let's go for it.

I wonder if making the sidebar full height (and thus moving the top bar) wouldn't be a good feedback in addition.

**Comment by Phillipus** [comment]
> I wonder if making the sidebar full height (and thus moving the top bar) wouldn't be a good feedback in addition.

Not sure what you mean?

**Comment by jbsarrodie** [comment]
>Not sure what you mean?

Something like that:
![image](https://user-images.githubusercontent.com/5757396/77431214-ad8aaa00-6ddc-11ea-81c7-8b4e3e8a3810.png)

**Comment by Phillipus** [comment]
Not sure how other UIs do it like that...will check...

**Comment by Phillipus** [comment]
I think like that it implies that the bottom area will hide?

**Comment by jbsarrodie** [comment]
And what about this : https://www.w3schools.com/w3css/tryit.asp?filename=tryw3css_sidebar_shift

**Comment by Phillipus** [comment]
I know you want to try that... ;-)

**Comment by jbsarrodie** [comment]
I've implemented the following changes:

When the sidebar is closed, we have an hamburger icon:
![image](https://user-images.githubusercontent.com/5757396/77760229-4700c880-7036-11ea-990e-445585ed6286.png)

And when the sidebar is opened, it takes the full height and shows a close icon:
![image](https://user-images.githubusercontent.com/5757396/77760291-60097980-7036-11ea-8bc3-2ac74749e9ff.png)

I think it makes more sens, so I'm commiting this (in fact it is already commited).

If someone want something else, then another issue will be created.

**Comment by Phillipus** [comment]
> If someone want something else,
 
I want gherkins with my hamburger...
