### ISSUE TITLE
Use link (hand) cursor in some places

### ISSUE THREAD

**Issue by Phillipus** [archi-contribs/jarchi-single-page-html-export#6]
I don't know if this is possible or just me nit-picking, but would it be possible to use the hand cursor on:

* The "X" and hamburger buttons
* The "Documentation", "Elements", "Relationships" tabs

**Comment by jbsarrodie** [comment]
That's possible and I did think the same. Will work on it.

**Comment by jbsarrodie** [comment]
Done ;-)

**Comment by Phillipus** [comment]
Tested, nice. ;-)
