### ISSUE TITLE
Ask for file name first?

### ISSUE THREAD

**Issue by Phillipus** [archi-contribs/jarchi-single-page-html-export#8]
As there can be a delay when the script is exporting images, do you think it makes sense to show the Save As dialog first? (In cases such as the user changing their mind, or sees that the file already exists)

**Comment by jbsarrodie** [comment]
Yes, that could make sens. As usual, this is opensource so you can contribute ;-)

**Comment by Phillipus** [comment]
> As usual, this is opensource so you can contribute ;-)

That's not how it works, you should know that. ;-)

**Comment by Phillipus** [comment]
Done.
